=== albernetr/dataModels/Sensor/MultisensoryDevice/schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "https://smartsdk.github.io/dataModels/Sensor/MultisensoryDevice/schema.json",
  "title": "FIWARE - Multisensory device schema",
  "description": "Represents a device that consist on a collection of sensors.",
  "type": "object",
  "references": [
    {
      "description": "This schema has been created to fulfil the need of provide a detailed description for each of the collection of sensor embebed into a device.",
      "url": "Pending to be included."
    }
  ],
  "definitions": {
    "id": {
      "$ref": "https://fiware.github.io/dataModels/common-schema.json#/definitions/EntityIdentifierType"
    },
    "type": {
      "description": "NGSI Entity type",
      "type": "string",
      "enum": [
        "MultisensoryDevice"
      ]
    },
    "name": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "category": {
      "type": "string"
    },
    "controlledProperty": {
      "type": "string"
    },
    "mnc": {
      "type": "string"
    },
    "mcc": {
      "type": "string"
    },
    "macAddress": {
      "type": "string"
    },
    "ipAddress": {
      "type": "string"
    },
    "supportedProtocol": {
      "type": "string"
    },
    "location": {
      "type": "array",
      "items": { 
        "$ref": "http://json-schema.org/geojson/geometry.json#" 
      }
    },
    "hardwareVersion": {
      "type": "string"
    },
    "softwareVersion": {
      "type": "string"
    },
    "firmwareVersion": {
      "type": "string"
    },
    "osVersion": {
      "type": "string"
    },
    "serialNumber": {
      "type": "number"
    },
    "provider": {
      "type": "string"
    },
    "batteryLevel": {
      "type": "string"
    },
    "deviceState": {
      "type": "string"
    },
    "refDeviceModel": {
      "$ref": "https://fiware.github.io/dataModels/common-schema.json#/definitions/EntityIdentifierType"
    },
    "refSensor": {
      "type": "array",
      "items": {
        "$ref": "https://fiware.github.io/dataModels/common-schema.json#/definitions/EntityIdentifierType"
      },
      "minItems": 1,
      "uniqueItems": true
    },
    "configuration": {
      "type": "object"
    },
    "dateManufactured": {
      "type": "string",
      "format": "date-time"
    },
    "dateInstalled": {
      "type": "string",
      "format": "date-time"
    },
    "dateLastCalibration": {
      "type": "string",
      "format": "date-time"
    },
    "dateModified": {
      "type": "string",
      "format": "date-time"
    },
    "dateCreated": {
      "type": "string",
      "format": "date-time"
    }
  },
  "properties": {
    "id": {
      "$ref": "#/definitions/id"
    },
    "type": {
      "$ref": "#/definitions/type"
    },
    "name": {
      "$ref": "#/definitions/name"
    },
    "description": {
      "$ref": "#/definitions/description"
    },
    "category": {
      "$ref": "#/definitions/category"
    },
    "controlledProperty": {
      "$ref": "#/definitions/controlledProperty"
    },
    "mnc": {
      "$ref": "#/definitions/mnc"
    },
    "mcc": {
      "$ref": "#/definitions/mcc"
    },
    "macAddress": {
      "$ref": "#/definitions/macAddress"
    },
    "ipAddress": {
      "$ref": "#/definitions/ipAddress"
    },
    "supportedProtocol": {
      "$ref": "#/definitions/supportedProtocol"
    },
    "location": {
      "$ref": "#/definitions/location"
    },
    "hardwareVersion": {
      "$ref": "#/definitions/hardwareVersion"
    },
    "softwareVersion": {
      "$ref": "#/definitions/softwareVersion"
    },
    "osVersion": {
      "$ref": "#/definitions/osVersion"
    },
    "firmwareVersion": {
      "$ref": "#/definitions/firmwareVersion"
    },
    "serialNumber": {
      "$ref": "#/definitions/serialNumber"
    },
    "provider": {
      "$ref": "#/definitions/provider"
    },
    "batteryLevel": {
      "$ref": "#/definitions/batteryLevel"
    },
    "deviceState": {
      "$ref": "#/definitions/deviceState"
    },
    "refDeviceModel": {
      "$ref": "#/definitions/refDeviceModel"
    },
    "refSensor": {
      "$ref": "#/definitions/refSensor"
    },
    "configuration": {
      "$ref": "#/definitions/configuration"
    },
    "dateManufactured": {
      "$ref": "#/definitions/dateManufactured"
    },
    "dateInstalled": {
      "$ref": "#/definitions/dateInstalled"
    },
    "dateLastCalibration": {
      "$ref": "#/definitions/dateLastCalibration"
    },
    "dateModified": {
      "$ref": "#/definitions/dateModified"
    },
    "dateCreated": {
      "$ref": "#/definitions/dateCreated"
    }
  },
  "required": [
    "id",
    "type",
    "refDeviceModel",
    "refSensor",
    "dateCreated"
  ]
}

=== albernetr/dataModels/Sensor/MultisensoryDevice/example.json
{
  "id": "device-9845A",
  "type": "MultisensoryDevice",
  "category": "smartphone",
  "controlledProperty": "accelerometer",
  "osVersion": "Android 4.0",
  "softwareVersion": "MA-Test 1.6",
  "hardwareVersion": "GP-P9872",
  "firmwareVersion": "SM-A310F",
  "refDeviceModel": "mySensor-sensor-345",
  "refSensor":[
    "sensor-9845A",
    "sensor-9845B",
    "sensor-9845C"
  ],
  "dateCreated": "2016-08-22T10:18:16Z"
}
